# -*- coding: utf-8 -*-
"""ChatBot 1.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11O3SR2_5iXTubWzUnhNLqPNo4q2_H8F0
"""

!pip install transformers gradio

from transformers import pipeline
import gradio as gr

# Carga el modelo FLAN-T5 base
qa = pipeline("text2text-generation", model="google/flan-t5-base")

def responder(pregunta):
    respuesta = qa(pregunta, max_length=100)[0]["generated_text"]
    return respuesta

iface = gr.Interface(fn=responder, inputs="text", outputs="text")
iface.launch()